# Generated by Django 4.2 on 2023-04-10 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=30)),
                ('password_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passwd_manager_app.passwordsets')),
            ],
        ),
    ]
