# Generated by Django 4.2 on 2023-04-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwd_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='user',
        ),
    ]
